<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.HttpClientTestExtensions"/>
    <PackageReference Include="Aspire.Hosting.Testing"/>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aiva.Admin.Api.AspireHost\Aiva.Admin.Api.AspireHost.csproj" />
    <ProjectReference Include="..\..\src\Aiva.Admin.Api.Infrastructure\Aiva.Admin.Api.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Aiva.Admin.Api.Web\Aiva.Admin.Api.Web.csproj" />
  </ItemGroup>

</Project>
